defaults: &defaults
  token: d77d65f2f8a2ee751d816683e05a8ea2167321958a1bb5e951022317eba0835b9f1229c3eecac185584af3b61262e390b195dee85610b672bcc1492fb9e2f816
  app_name: Teaching Ministry Manager demo site
  noreply: noreply@fs-rails3-base.heroku.com
  host: localhost:3000
  identities:
    google_apps:
      icon: social-icons/google_64.png
    yahoo:
      icon: social-icons/yahoo_64.png
    twitter:
      key: Ank92dam8rUTSfBtxN7AWg
      secret: kl95VO9BWzb6a4NL8dZJbosJMm4kmiGPoC0LKvdV6OI
      icon: social-icons/twitter_64.png
    facebook:
      key: 147749211905466
      secret: b682557c3bc08512d09ebc4b848d8d93
      icon: social-icons/facebook_64.png

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: fs-rails3-base.heroku.com
